spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://123.2.134.36:3306/unityalert_db
    username: altong
    password: dkfxhd4#2!
    initialize: false
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 13108

logging:
  config: classpath:logback-spring-dev.xml