spring:
  profiles:
    active: h2
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/unityalert_db
    username: uauser
    password: xhdgkqdkfflatltmxpa4321
    tomcat:
      max-active: 10
      max-idle: 5
      min-idle: 2
      max-wait: -1
      initial-size: 5
      remove-abandoned: true
      remove-abandoned-timeout: 60
      validation-query: SELECT 1 FROM DUAL
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:[%5p]}) %m%n"
  level:
    root: INFO
    kr.co.daou.sdev.altong: DEBUG

# actuator 설정
management:
  security:
    enabled: false

security:
  basic:
    enabled: false
  ignored: "/**"

# sendworker thread수
send:
  worker:
    count: 8

# 스케줄    
scheduled:
  connection: 5000
  first: 3000
  second: 5000
  static: "0 0/30 8-20 * * MON-SAT"
